### ISSUE TITLE
Create FAKE target for releases

### ISSUE THREAD

**Issue by rneatherway** [fsprojects/projekt#16]

**Comment by kjnilsson** [comment]
Wouldn't a zip be more appropriate?

**Comment by kjnilsson** [comment]
How should we bundle the templates? I think I need to make a code change to make sure they are found for the init command.

**Comment by kjnilsson** [comment]
Submitted a PR that should find the templates directory if it is in the same location as the exe.

**Comment by rneatherway** [comment]
Actually, yes I think a zip would be better. I can add the logic I use for fsautocomplete (all it does is create the zip and tell you what to paste where on the release page). forki was pretty keen on the NuGet idea (https://github.com/fsharp/vim-fsharp/issues/7) so we could maybe do that later.

For the templates I think they should be either in the same directory or a subdirectory of where `Projekt.exe` is. We could use the msbuild `Copy` task for that.

**Comment by rneatherway** [comment]
Actually, I think I will just add the zip stuff to create the archive, and use the Octokit thing. I want to know how to use it and it would mean no more manual copy and pasting to create the release -- just building a FAKE target.

**Comment by rneatherway** [comment]
So to release the process is http://fsprojects.github.io/ProjectScaffold/release-process.html

You have to create another `build.sh` file containing your github username/pw, or set them as env variables, and be 100% sure it is in the .gitignore file as the release process commits, tags and pushes. I might look later at improving build.fsx from ProjectScaffold so it can quiz for the github username/pw.

It is then just a question of updating RELEASE_NOTES.md so that the top entry has the version number for the release and AssemblyFileInfo.fs is automatically updated.

**Comment by rneatherway** [comment]
So this is done.
