### ISSUE TITLE
fails to load templates on linux

### ISSUE THREAD

**Issue by yawnt** [fsprojects/projekt#29]
first, thank you for this tool, i can't express how vital it is for someone who only wants to deal with emacs ;P !!

i tried installing it on linux and the only way i could get it to successfully create a project is to run it from the actual folder because it looks like it uses relative paths to figure out where the templates are

eg:

```
┌(yawnt@ehecatl) (iojs 1.2.0)
╰─(/tmp)> ~/.projekt/bin/Projekt/Projekt.exe init /tmp/potatoes/MyProject.fsproj --template console --organisation MyOrganisation                                                                              1 ↵
err: failed to copy /tmp/templates/Console/Console.fsproj to /tmp/potatoes/MyProject.fsproj. Message: /tmp/templates/Console/Console.fsproj does not exist
```

**Comment by rneatherway** [comment]
Hi, thanks for the bug report. We're still early in development so sorry for these rough edges. I'll give this a try tomorrow and hopefully push a fix.

**Comment by rneatherway** [comment]
@yawnt, I've got a fix, so hopefully a new release later today. I am planning to integrate this tool into Emacs, so if you have any suggestions for how that could work, or you would like to help, that would be great!

**Comment by yawnt** [comment]
terrific, I'll check it out tomorrow! don't worry bout the rough edges, it's part of the fun! thank you very much

honestly I'm pretty new to this .NET thing, but F# is quite the compelling argument, so I don't have many suggestions right off the bat, but I guess the more I use it, the more stuff will come up!

(one thing that did cause me pain is, I have no idea what the default layout for a F# project is, since I don't use VisualStudio or MonoDevelop, and I'm trying to figure out how FAKE, Paket and Projekt all fit together, but it's probably not Projekt's goal to also be a scaffold generator (eg: include some default paket.dependencies etc) ?)

**Comment by kjnilsson** [comment]
Merged - hopefully it will work ok now. :)
