### ISSUE TITLE
init does not understand --frameworkversion

### ISSUE THREAD

**Issue by rneatherway** [fsprojects/projekt#8]

**Comment by kjnilsson** [comment]
I'll do this next.

**Comment by rneatherway** [comment]
Cool, OK. My PR has changed a few things so might be worth checking everything still makes sense there first though.

**Comment by kjnilsson** [comment]
Pr submitted

**Comment by kjnilsson** [comment]
also added an arg for organisation

**Comment by rneatherway** [comment]
Fixed by #11
